version: "3"

volumes:
  pg_data: {}

services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data:Z

  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    command: sh -c "./wait_db.sh db:5432 --
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:80"
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure
