# Generated by Django 3.2 on 2021-09-12 02:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectdetectionsample',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 9, 12, 2, 34, 57, 839627, tzinfo=utc)),
        ),
    ]
