# Generated by Django 3.2 on 2021-09-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_objectdetectionsample_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdetectionsample',
            name='image_url',
            field=models.URLField(default='3ewqqwe'),
            preserve_default=False,
        ),
    ]
