# Generated by Django 3.2 on 2021-09-11 23:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_project_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_ad',
            field=models.DateField(default=datetime.date(2021, 9, 11)),
        ),
    ]
