# Generated by Django 3.2 on 2021-09-12 10:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210912_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='objectdetectionsample',
            name='is_image_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 9, 12, 10, 34, 21, 156189, tzinfo=utc)),
        ),
    ]
