# Generated by Django 3.2 on 2021-09-11 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_created_ad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_ad',
            field=models.DateField(default=datetime.datetime(2021, 9, 11, 23, 9, 30, 486400, tzinfo=utc)),
        ),
    ]
