# Generated by Django 3.2 on 2021-09-11 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_project_created_ad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_ad',
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 9, 11, 23, 9, 39, 237308, tzinfo=utc)),
        ),
    ]
